import re

path = 'c:/Users/DELL/Desktop/BUGRA/ArcRise/arcrise.html'
with open(path, 'rb') as f:
    data = f.read()

# Map of double-encoded UTF-8 bytes -> proper UTF-8 bytes for the original char.
# Each entry: bytes-as-they-appear-now -> bytes-of-the-original-codepoint
# Generated by encoding U+XXXX in UTF-8, mis-decoding as Windows-1252,
# then re-encoding as UTF-8 (the corruption that happened).
def double_encoded(ch):
    """Return the corrupted byte sequence that `ch` would become after
    one UTF-8 -> Win-1252 -> UTF-8 round trip."""
    utf8_bytes = ch.encode('utf-8')
    try:
        latin_str = utf8_bytes.decode('cp1252')
    except UnicodeDecodeError:
        # cp1252 has undefined codepoints; use latin-1 fallback for those
        latin_str = utf8_bytes.decode('latin-1')
    return latin_str.encode('utf-8')

# Characters to repair (most-visible to most-cosmetic)
chars_to_fix = [
    '·',  # · middle dot
    '¢',  # ¢ cent
    '©',  # ©
    '®',  # ®
    '—',  # — em dash
    '–',  # – en dash
    '•',  # • bullet
    '‘',  # ' left single quote
    '’',  # ' right single quote
    '“',  # " left double quote
    '”',  # " right double quote
    '…',  # … ellipsis
    '™',  # ™
    '×',  # × multiplication sign
    '→',  # → right arrow
    '←',  # ← left arrow
    '↑',  # ↑
    '↓',  # ↓
    '↔',  # ↔
    '↕',  # ↕
    '●',  # ● black circle
    '○',  # ○ white circle
    '◀',  # ◀
    '▶',  # ▶
    '▲',  # ▲
    '▼',  # ▼
    '✓',  # ✓
    '✗',  # ✗
    '✅',  # ✅
    # Box drawing (used in CSS comment dividers)
    '═', '║', '╔', '╗', '╚', '╝',  # ═ ║ ╔ ╗ ╚ ╝
    '─', '│', '┌', '┐', '└', '┘',  # ─ │ ┌ ┐ └ ┘
    '▀', '▄', '█', '▌', '▐',
    ' ',  # NBSP — appears sometimes
]

# Build replacement list — longest pattern first so multi-byte sequences match
# before any shorter potential collisions.
pairs = [(double_encoded(c), c.encode('utf-8')) for c in chars_to_fix]
pairs.sort(key=lambda p: -len(p[0]))

before_size = len(data)
fixed_count = 0
for corrupted, proper in pairs:
    cnt = data.count(corrupted)
    if cnt:
        data = data.replace(corrupted, proper)
        fixed_count += cnt
        print(f'{cnt:5}x  {corrupted.hex():<24} -> {proper.decode("utf-8")!r}')

# Also: triple-encoded patterns (chars that went through corruption twice)
# Try one more round for the most common: ●, ·
triple_chars = ['●', '·', '○']
for c in triple_chars:
    once = double_encoded(c)
    twice_str = once.decode('cp1252', errors='replace')
    twice = twice_str.encode('utf-8')
    if twice != once:
        cnt = data.count(twice)
        if cnt:
            data = data.replace(twice, c.encode('utf-8'))
            fixed_count += cnt
            print(f'{cnt:5}x  TRIPLE {twice.hex():<22} -> {c!r}')

with open(path, 'wb') as f:
    f.write(data)

print(f'\nTotal: {fixed_count} replacements. File size: {before_size} -> {len(data)}')
